// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Signin() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex h-[94vh] items-center justify-center bg-[rgb(2,48,32)]\"><div class=\"w-full max-w-md space-y-8 bg-white p-8 shadow-md md:rounded-lg\" x-data=\"{ loading: false }\"><div class=\"text-center\"><h1 class=\"mb-6 text-4xl font-extrabold tracking-tight lg:text-5xl\">Sign in to use AI</h1><p class=\"mb-4\">Sign in to continue your secret conversations</p></div><!-- FORM --><form hx-post=\"/signinBackend\" @submit=\"loading = true\" class=\"space-y-6\"><div class=\"space-y-2\"><label for=\"identifier\">Email/Username</label> <input name=\"identifier\" id=\"identifier\" type=\"text\" class=\"flex h-10 w-full rounded-md border px-3 py-2 text-sm\"></div><div class=\"space-y-2\"><label for=\"password\">Password</label> <input name=\"password\" id=\"password\" type=\"password\" class=\"flex h-10 w-full rounded-md border px-3 py-2 text-sm\"></div><button type=\"submit\" class=\"bg-black text-white h-10 w-full rounded-md\"><span x-show=\"!loading\">Sign In</span> <span x-show=\"loading\">Signing in...</span></button></form><!-- RESPONSE --><div id=\"auth-response\"></div><!-- LINKS --><div class=\"flex\"><a href=\"/forgot-password\" class=\"text-blue-600\">Forgot Password?</a><div class=\"grow\"></div><a href=\"/sign-up\" class=\"text-blue-600\">Sign up</a></div><!-- GOOGLE LOGIN --><button hx-get=\"/auth/google\" hx-trigger=\"click\" class=\"bg-black text-white h-10 w-full rounded-md flex items-center justify-center gap-2\"><img src=\"/public/google.png\" class=\"h-5 w-5\"> Log in with Google</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
