// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func VerifyAccount(username string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex h-[94vh] items-center justify-center bg-gray-100\"><div class=\"w-full max-w-md space-y-8 rounded-lg bg-white p-8 shadow-md\" x-data=\"{ loading: false }\"><div class=\"text-center\"><h1 class=\"mb-6 text-4xl font-extrabold tracking-tight lg:text-5xl\">Verify Your Account</h1><p class=\"mb-4\">Enter the verification code sent to your email</p></div><form class=\"space-y-6\" hx-post=\"/verify-code-backend\" hx-target=\"#verify-response\" hx-swap=\"innerHTML\" x-on:submit=\"loading = true\"><input type=\"hidden\" name=\"username\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/VerifyAccount.templ`, Line: 24, Col: 57}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><div class=\"space-y-2\"><label class=\"text-sm font-medium\" for=\"verify\">Verification Code</label> <input id=\"verify\" name=\"code\" type=\"text\" required class=\"flex h-10 w-full rounded-md border px-3 py-2 text-sm\"></div><button type=\"submit\" class=\"bg-black text-white h-10 w-full rounded-md\"><span x-show=\"!loading\">Verify</span> <span x-show=\"loading\">Verifying...</span></button></form><!-- Response container (like toast replacement) --><div id=\"verify-response\" class=\"text-center text-sm mt-4\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
