

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weber
  labels:
    app: weber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weber
  template:
    metadata:
      labels:
        app: weber
    spec:   

      volumes:
        - name: workspace-volume
          emptyDir: {}

      initContainers:
        - name: file-fetcher
          image: meeran666/file_accepter
          env:
            - name: BASE_FOLDER
              value: "weber"
            - name: MODE
              value: "init"
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace

      containers:
        - name: runner
          image: meeran666/ide_image_html
          ports:
            - containerPort: 3006
            - containerPort: 3000
          env:
            - name: GOLET_ID
              value: "weber"
            - name: WORKSPACE_NAME
              value: "solar"
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: weber
spec:
  selector:
    app: weber
  ports:
    - protocol: TCP
      name: ws
      port: 3006
      targetPort: 3006
    - protocol: TCP
      name: user
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weber
spec:
  ingressClassName: nginx
  rules:
    - host: weber.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weber
                port:
                  number: 3006

    - host: down.weber.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weber
                port:
                  number: 3000