

apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
  labels:
    app: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
  template:
    metadata:
      labels:
        app: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
    spec:   

      volumes:
        - name: workspace-volume
          emptyDir: {}

      initContainers:
        - name: file-fetcher
          image: meeran666/file_accepter
          env:
            - name: BASE_FOLDER
              value: "meeran-e20fce22-dc22-439f-901f-4bf59a71662d"
            - name: MODE
              value: "init"
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace

      containers:
        - name: runner
          image: meeran666/ide_image_node
          ports:
            - containerPort: 3006
            - containerPort: 3000
          env:
            - name: GOLET_ID
              value: "meeran-e20fce22-dc22-439f-901f-4bf59a71662d"
            - name: WORKSPACE_NAME
              value: "solar "
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
spec:
  selector:
    app: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
  ports:
    - protocol: TCP
      name: ws
      port: 3006
      targetPort: 3006
    - protocol: TCP
      name: user
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
spec:
  ingressClassName: nginx
  rules:
    - host: meeran-e20fce22-dc22-439f-901f-4bf59a71662d.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
                port:
                  number: 3006

    - host: down.meeran-e20fce22-dc22-439f-901f-4bf59a71662d.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meeran-e20fce22-dc22-439f-901f-4bf59a71662d
                port:
                  number: 3000